name: SKIBlock
version: 1.0
main: com.pixl8.skiblock.SKIBlock
api-version: 1.20

commands:
  createsbworld:
    description: Creates a new SkyBlock world
    permission: skiblock.admin
  stp:
    description: Start your SkyBlock adventure
    permission: skiblock.use
  sborder:
    description: Set your border size and center.
    permission: skiblock.admin
